### ISSUE TITLE
Not running conversion, no feedback or errors

### ISSUE THREAD

**Issue by thehoegh** [logzio/influxql-to-promql-converter#3]
# What can we help you with?

For some dashboards I'm trying to convert, the converter doesn't trigger any error messages even though no output is produced. The result_report.yml file reads the name of the dashboard input. The input dashboards are valid Grafana dashboards that have been produced by exporting the grafana json. 

I'm using a source folder in the config.yml
```sh
importer:
  folder:
    path: influxboard # relative or full path
exporter:
  folder:
    path: grafanaboard # relative or full path
```

The resulting terminal output:

```sh
INFO:__main__:Starting to fetch dashboards from importer: <importer.folder.folder_importer.FolderImporter object at 0x100a51cd0>
INFO:__main__:Exporting dashboards with exporter: <exporter.folder.folder_exporter.FolderExporter object at 0x100a35d10>
INFO:__main__:Finished converting 0 dashboards
INFO:__main__:Building result report
INFO:__main__:Finished building result report: result_report.yaml
INFO:__main__:Finished running in --- 0.006732940673828125 seconds ---
```

**Comment by dg-nvm** [comment]
The result report should show you why it wasn't converted. If this won't show what is the problem, it would really help if you could publish dashboard.json for this, I have heavily modified version for our internal usage and it fixes few issues with conversion.

**Comment by 8naama** [comment]
Hey @holene! 

Based on the log `converting 0 dashboards` it seems like the script did not find dashboards in the specified path, please try to use the full path to the folder and let us know how it goes

**Comment by 8naama** [comment]
Hey @holene!

I'll close this ticket as stale, but in case still relevant you can reopen here, or reach out to our support for faster replies via the chat icon in your account or at the docs in the bottom left:
https://docs.logz.io/docs/user-guide/quick-start
![image](https://github.com/user-attachments/assets/975f47a3-739d-43df-ab5d-5a39fe159396)
